version: '2'

services:
  nginx:
    image: azuracast/azuracast_nginx:latest
    ports:
      - '81:80'
      - '444:443'
    depends_on:
      - web
      - stations
    volumes:
      - .:/var/azuracast/www
    restart: always

  mariadb:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=azuracast
      - MYSQL_PASSWORD=azur4c457
      - MYSQL_DATABASE=azuracast
    restart: always

  influxdb:
    image: influxdb:alpine
    volumes:
      - influx_data:/var/lib/influxdb
    restart: always

  redis:
    image: redis:alpine
    restart: always

  web:
    image: azuracast/azuracast_web:latest
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    volumes:
      - .:/var/azuracast/www
      - tmp_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
    restart: always

  cron:
    container_name: azuracast_cron
    image: azuracast/azuracast_web:latest
    volumes_from:
      - web
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    command: 'cron && tail -f /var/log/cron.log'
    restart: always

  cli:
    image: azuracast/azuracast_web:latest
    volumes_from:
      - web
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    command: 'bash'

  stations:
    container_name: azuracast_stations
    image: azuracast/azuracast_stations:latest
    ports:
     - '8000:8000'
     - '8005:8005'
     - '8006:8006'
     - '8010:8010'
     - '8015:8015'
     - '8016:8016'
     - '8020:8020'
     - '8025:8025'
     - '8026:8026'
     - '8030:8030'
     - '8035:8035'
     - '8036:8036'
     - '8040:8040'
     - '8045:8045'
     - '8046:8046'
     - '8050:8050'
     - '8055:8055'
     - '8056:8056'
     - '8060:8060'
     - '8065:8065'
     - '8066:8066'
     - '8070:8070'
     - '8075:8075'
     - '8076:8076'
     - '8080:8080'
     - '8085:8085'
     - '8086:8086'
     - '8090:8090'
     - '8095:8095'
     - '8096:8096'
    volumes:
     - station_data:/var/azuracast/stations
    restart: always

volumes:
  db_data: {}
  influx_data: {}
  station_data: {}
  tmp_data: {}
